# -*- coding: utf-8 -*-
"""AI LAB1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eVjHp2KnPu51HiUz5ArUDwfZJdZBywKt
"""

print("Usama Yousaf")

a = 5

b = 10

"""✈

Usama Yousaf

*Addition*
Now We have add these two variables which we have assign numbers to it.
"""

a + b

"""Subtraction
Perform subtraction on these numbers
"""

a - b

"""*Multiplication*  This code perform multiplication of numbers"""

a * b

"""Division
This code is used to devide two numbers
"""

b/a