# -*- coding: utf-8 -*-
"""AI LAB1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eVjHp2KnPu51HiUz5ArUDwfZJdZBywKt
"""

print("Usama Yousaf")

a = 5

b = 10

"""✈

Usama Yousaf

Addition
"""

a + b

"""Subtraction"""

a - b

"""Multiplication"""

a * b

"""Division"""

b/a