# -*- coding: utf-8 -*-
"""LAB2 Task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ST2zNCOuZ71ydZtGfknEatz_GnnVzfB8
"""



"""Text

Matplpotlib
"""

import matplotlib.pyplot as plt

data = [2, 4, 6, 8, 10]
data2 = [10, 20, 30, 40, 50]

plt.plot(data, data2, marker='o')
plt.xlabel("X-axis values")
plt.ylabel("Y-axis values")
plt.title("Simple Line Plot")
plt.grid(True)
plt.show()

"""Dictionary"""

students = [
    {"Name": "Usama", "Marks": 90},
    {"Name": "Ahmad", "Marks": 80},
    {"Name": "Ali", "Marks": 85}
]

print(students)

students[1]["Name"] = "Aslam"

print(students)

"""Numpy

Tuple
"""

fistTuple  = ("Ali", "Hamza", "Salman")
print(fistTuple)
mylist = list(fistTuple)
print(mylist)

"""Set"""

from typing import Union
set1 = {1,2,3,4,5}

set2 = {6, 7, 8,5}

Union = set1.union(set2)
print("Union: ",Union)

Intersection = set1.intersection(set2)
print("Intersection: ",Intersection)

diff = set1.difference(set2)
print("Difference: ",diff)

set1.remove(2)
print(set1)

set2.add(9)
print(set2)

"""List"""

list = [1,2,3,4,5,6,7,8,9,10]
print(list)
print('Sum: ',sum(list))
print('Maximum: ',max(list))
print('Minimum: ',min(list))